config/routes.rb
Permalinq::Application.routes.draw do
  resources :events
  resources :projects

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :relevances
  has_many :projects, :through => :relevances

  default_scope order("date DESC")
  scope :upcoming, where('date >= ?', DateTime.now).order('date ASC').limit(2)
  scope :recent, where('date < ?', DateTime.now).limit(5)

  attr_accessible :date, :description, :location, :name, :project_ids
  validates :date, :presence => true
  validates :name, :presence => true

  def future?
    return date > DateTime.now
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :relevances
  has_many :events, :through => :relevances, :order => "date DESC"

  default_scope order('name ASC')
  scope :popular, :order => 'updated_at DESC', :limit => 3

  attr_accessible :description, :name

  def self.fake_related
    [{ :name => 'Permasite', :group => 'UMass',
      :description => 'A nationally recognized permaculture garden.' },
     { :name => 'Food Forest', :group => 'Transition SLO',
      :description => 'A great project.' }]
  end
end

app/models/relevance.rb
class Relevance < ActiveRecord::Base
  belongs_to :project
  belongs_to :event
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_projects

  def load_projects
    @projects = Project.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.project_ids = params[:project]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @top_projects = Project.unscoped.popular
    @upcoming_events = Event.unscoped.upcoming
    @recent_events = Event.recent
    @related_projects = Project.fake_related
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @events = @project.events

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/events/_event.html.erb
<%= content_tag :div, :class => ['event', ('future' if event.future?)] do %>

  <h3><%= link_to event.name, event %></h3>

  <div class="info">
    <div class="date"><%= l event.date, :format => :long %></div>
    <div><%= event.location %></div>
  </div>


  <ul class="photos thumbnails">
    <% 3.times do %>
      <li class="span4">
        <img src="http://lorempixel.com/240/180/nature" class="img-rounded">
      </li>
    <% end %>
  </ul>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-error">
      <strong><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</strong>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :projects, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :project_ids, @projects, :id, :name, {},
        :class => 'chzn-select', :multiple => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls datetime">
      <%= f.datetime_select :date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows => 5 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<p>
  <%= link_to new_event_path, :class => 'btn btn-primary' do %>
    <span class="icon-plus"></span>
    New event
  <% end %>
</p>

<%= render :partial => 'event', :collection => @events %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<% content_for :title, @event.name %>

<%- model_class = Event -%>
<div class="page-header">
  <h1><%= @event.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @event.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @event.location %></dd>
</dl>

<p>
  <%= @event.description %>
</p>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<div class="span6">
  <div class="homesec">
    <h2>Upcoming</h2>
    <% @upcoming_events.each do |event| %>
      <div class="homebox">
        <h3><%= link_to event.name, event %></h3>
        <p><%= l event.date, :format => :long %></p>
      </div>
    <% end %>
  </div>
  <div class="homesec">
    <h2>Recent</h2>
    <% @recent_events.each do |event| %>
      <div class="homebox">
        <div class="row-fluid">
          <div class="span8">
            <h3><%= link_to event.name, event %></h3>
            <p><%= l event.date, :format => :long %></p>
          </div>
          <div class="span4">
            <img src="http://lorempixel.com/160/120/nature" class="img-rounded">
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="span6">
  <div class="homesec">
    <h2>Projects</h2>
    <% @top_projects.each do |project| %>
      <div class="homebox">
        <h3><%= link_to project.name, project %></h3>
        <p><%= truncate(project.description, :length => 100, :separator => ' ') %></p>
      </div>
    <% end %>
  </div>
  <div class="homesec">
    <h2>Related</h2>
    <% @related_projects.each do |project| %>
      <div class="homebox">
        <h3><%= link_to project[:group], '#' %> / <%= link_to project[:name], '#' %></h3>
        <p><%= project[:description] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + ' | Permalinq' : "Permalinq" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">Permalinq</a>
          <div class="container-fluid">
            <ul class="nav">
              <li><%= link_to "Projects", projects_path  %></li>
              <li><%= link_to "Events", events_path  %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3 hidden-phone">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Projects</li>
              <% @projects.each do |project| %>
                <%= content_tag :li, link_to(project.name, project),
                  :class => ("active" if current_page?(project)) %>
              <% end %>
              <%= content_tag :li,
                :class => ("active" if current_page?(new_project_path)) do %>
                <%= link_to new_project_path do %>
                  <span class="icon-plus"></span>
                  New project
                <% end %>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows => 5 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<% content_for :title, @project.name %>

<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @project.name %></h1>
</div>

<p>
  <%= @project.description %>
</p>

<p>
  <%= link_to new_event_path(:project => @project.id), :class => 'btn btn-primary' do %>
    <span class="icon-plus"></span>
    New event
  <% end %>
  <%= link_to 'Edit project', edit_project_path(@project), :class => 'btn'%>
</p>

<%= render :partial => "events/event", :collection => @events %>